// This file was auto-generated by Fern from our API Definition.

export const CatalogWellKnownModelProviderType = {
    Openai: "openai",
    Anthropic: "anthropic",
    GoogleGemini: "google-gemini",
    Fireworks: "fireworks",
    Zai: "zai",
    Moonshot: "moonshot",
    Alibaba: "alibaba",
    Together: "together",
    Truefoundry: "truefoundry",
} as const;
export type CatalogWellKnownModelProviderType =
    (typeof CatalogWellKnownModelProviderType)[keyof typeof CatalogWellKnownModelProviderType];
