// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ConfiguredModel {
    /** Upstream, provider-specific identifier sent to the provider API. May contain `/`. */
    modelId: string;
    /** Configured model name. May contain `/` (e.g. `account/model` on TrueFoundry). */
    name: string;
    properties: TrueForge.ModelProperties;
}
