// This file was auto-generated by Fern from our API Definition.

export interface ModelProvidersCapability {
    /** Whether in-app model provider settings are enabled. False when models come from TrueFoundry. */
    enabled: boolean;
}
