// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface SettingsCapability {
    /** Whether the settings UI/API is enabled. */
    enabled: boolean;
    modelProviders: TrueForge.ModelProvidersCapability;
}
