// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ModelProperties } from "./ModelProperties.js";

export const ConfiguredModel: core.serialization.ObjectSchema<
    serializers.ConfiguredModel.Raw,
    TrueForge.ConfiguredModel
> = core.serialization.object({
    modelId: core.serialization.property("model_id", core.serialization.string()),
    name: core.serialization.string(),
    properties: ModelProperties,
});

export declare namespace ConfiguredModel {
    export interface Raw {
        model_id: string;
        name: string;
        properties: ModelProperties.Raw;
    }
}
