// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelProvidersCapability: core.serialization.ObjectSchema<
    serializers.ModelProvidersCapability.Raw,
    TrueForge.ModelProvidersCapability
> = core.serialization.object({
    enabled: core.serialization.boolean(),
});

export declare namespace ModelProvidersCapability {
    export interface Raw {
        enabled: boolean;
    }
}
